eclipse-che/che-website

README.md, devfile.yaml
Signed-off-by: Sun Tan <sutan@redhat.com>
=> adding devfile

che/includes/footer.php
Signed-off-by: Jesse Williams <jessewilliams.r@gmail.com>
=> updated footer links

che/index.php
Signed-off-by: Jesse Williams <jessewilliams.r@gmail.com>
=> updated hero h1

devfile.yaml
Signed-off-by: Sun Seng David TAN <sutan@redhat.com>
=> fix user issue avoid entrypoint to be overriden

che/chectl/index.php
Related to https://github.com/eclipse/che/issues/14114
Change-Id: Icc274f2dd869466a651a703509fb42f5dac7a9e4
Signed-off-by: Florent Benoit <fbenoit@redhat.com>
=> chore(chectl): Add install script redirect

che/getting-started/cloud-osio/scripts/factories.json, che/getting-started/cloud/scripts/factories.json
Related issue https://github.com/redhat-developer/rh-che/issues/1553
=> rh-che #1553: Re-generating Che factories after account deactivation on che.openshift.io

che/chectl/win/index.php
Related to https://github.com/eclipse/che/issues/14114
Change-Id: I1b4f5d5a86757fc2ae5044665b54b19c91e743f3
Signed-off-by: Florent Benoit <fbenoit@redhat.com>
=> chore(chectl): Add windows install script redirect

che/technology/index.php
This PR remove the silent videos which were based on Che 6
=> Remove the silent videos section

che/technology/index.php
Update the technology page with content more specific to Che 7
=> Update technology page

che/index.php
https://github.com/eclipse/che/issues/15238
=> che #15238 Updating links with devfile references on the homepage

che/getting-started/index.php, che/index.php
Signed-off-by: Sun Tan <sutan@redhat.com>
=> update links to the documentation

che/extend/index.php
Fixes https://github.com/eclipse/che/issues/15229
=> Point to Hosted Che Swagger. Fixes che/issues/15229

che/index.php
This PR could be run with http://che.openshift.io/factory?url=https://github.com/eclipse/che-website/tree/fix-header-title
=> Fix header title

che/getting-started/cloud-osio-preview/index.php, che/getting-started/cloud-osio/index.php, che/getting-started/cloud/index.php, che/getting-started/download/index.php, che/getting-started/index.php, che/index.php
Related issue https://github.com/eclipse/che/issues/18463
Try it on Hosted Che
[![Contribute](https://www.eclipse.org/che/contribute.svg)](https://che.openshift.io/f?url=https://github.com/ibuziuk/che-website)
=> che #18463 Adding clarification that Hosted Che is Eclipse Che hosted by Red Hat

che/features/index.php, che/index.php
Perform language/consistency cleanup
like removing 'machine', 'docker', etc
=> Perform language/consistency cleanup

che/extend/artik/index.php, che/extend/bitnami/index.php, che/extend/sap/index.php, che/extend/silexica/index.php, che/getting-started/cloud/index.php, che/getting-started/download/index.php, che/getting-started/index.php, che/includes/footer.php, che/includes/header.php, che/index.php, che/technology/index.php
Fix all links pointing to che-docs.
=> Fix links to che-docs

che/getting-started/cloud-osio/index.php, che/getting-started/cloud/index.php, che/index.php
Try it on Hosted Che
[![Contribute](https://www.eclipse.org/che/contribute.svg)](https://che.openshift.io/f?url=https://github.com/ibuziuk/che-website)
=> Adding Hosted Che EOL warning

che/getting-started/cloud-osio/index.php, che/getting-started/cloud/index.php, che/index.php
Try it on Hosted Che
[![Contribute](https://www.eclipse.org/che/contribute.svg)](https://che.openshift.io/f?url=https://github.com/ibuziuk/che-website/tree/eol_message_fixup)
=> Improving Hosted Che EOL message

che/getting-started/cloud/index.php
=> Fixing the 'Create a workspace from your GitHub or GitLab repo' flow

che/extend/index.php
=> Swagger link fixup

che/getting-started/cloud/scripts/factories.json, che/index.php
Should be applied together with the 2.8 rollout on workspaces.openshift.com
=> [DO NOT MERGE] Updating 'Getting Started' devfile samples to the product version 2.8

che/getting-started/cloud/scripts/factories.json, che/index.php
related to renaming in https://github.com/redhat-developer/codeready-workspaces/commit/2669e3f4848d0d43093ffe4aea81c66652ee4532#diff-019cad2689509a0[%E2%80%A6]d0451d7b5021b8fb2549
=> fix: updatig links for python devfile for CRW 2.14 release on workspaces.openshift.com

src/routes/features/index.svelte
=> Fix typo in flex:col

src/lib/try/TryOnline.svelte
[![Contribute (nightly)](https://img.shields.io/static/v1?label=nightly%20Che&message=for%20maintainers&logo=eclipseche&color=FDB940&labelColor=525C86)](https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com#https://github.com/eclipse-che/che-website/tree/ibuziuk-patch-1&storageType=ephemeral)
=> feat: Updating samples to the latest version of the product

src/lib/try/TryOnline.svelte
fixes https://github.com/eclipse/che/issues/21924
=> fix: using 'devspaces-3.3-rhel-8' branch for the downstream samples

README.md
=> doc: Updating README.md title

src/lib/try/TryOnline.svelte
=> chore: switching samples to 'devspaces-3.4-rhel-8'

.devfile.yaml, src/lib/try/TryInstall.svelte
=> Remove platforms that don't have installation doc

.github/workflows/publication-builder.yaml
new publication builder workflow
=> chore: new publication builder workflow

src/lib/try/TryOnline.svelte
https://workspaces.openshift.com#https://registry.devfile.io/devfiles/dotnet60/1.0.3&storageType=ephemeral
=> [DO NOT MERGE] feat: use .NET sample from registry.devfile.io
