che/getting-started/cloud/index.php
=> Replacing 'openshift.io' with 'che.openshift.io' on the 'getting-started' page

Jenkinsfile
For now, update on the website was performed with old eclipse CI
https://ci.eclipse.org/che/job/che-website-mirror
but this instance is gonna be removed and replaced by a new CI instance allowing to use containers
Here is a Jenkinsfile to publish website with new JIRO instance
Change-Id: I7241c3fdfffe0bc5e2b7e5d3c7e75852c7b6fac8
Signed-off-by: Florent Benoit <fbenoit@redhat.com>
=> chore(Jenkinsfile): Provide a Jenkinsfile for the ci.eclipse.org

che/features/index.php
We do not provide SSH Access, Mount-and-Sync or an electron client.
=> fix https://github.com/eclipse/che/issues/16220

che/getting-started/download/index.php, che/getting-started/index.php, che/includes/footer.php
The default quicks starts doc should be Che 7 - fixes https://github.com/eclipse/che/issues/14446
=> The default quicks starts doc should be Che 7

devfile.yaml, redirect.html
- removing not needed project source location
- adding gh plugin to facilitate contribution
- adding endpoint so Che does not need to perform a redirect and point to the right path
- removing the redirect trick
Signed-off-by: Sun Tan <sutan@redhat.com>
=> Improving devfile:

che/getting-started/cloud/scripts/factories.json
Updating the devfile samples to 'crw-2.6-rhel-8' branch - https://github.com/redhat-developer/codeready-workspaces/tree/crw-2.6-rhel-8/dependencies/che-devfile-registry/devfiles
=> Updating the devfile samples to 'crw-2.6-rhel-8' branch

src/lib/try/TryOnline.svelte
Signed-off-by: ibuziuk <ibuziuk@che>
=> feat: Adding 'ephemeral' parameter for the Getting Started samples

src/lib/try/TryOnline.svelte
Using https://github.com/che-incubator/quarkus-api-example as a default quarkus getting-started sample
=> feat: Using quarkus-api-example as a getting-started sample

src/lib/try/TryOnline.svelte
Signed-off-by: Vitaliy Gulyy <vgulyy@redhat.com>
Replaces **rest-http-example** example with https://github.com/che-samples/java-spring-petclinic/tree/devfilev2
Solves https://github.com/eclipse/che/issues/21937
=> chore: replace devspaces-samples/rest-http-example with che-samples/java-spring-petclinic

.devfile.yaml
Use the latest universal developers image. In my testing for `podman build` using the che-website devfile, I encountered build errors that were resolved by updating the UDI.
=> Use latest UDI image

src/routes/extend/index.svelte, src/routes/features/index.svelte, src/routes/getting-started/cloud/index.svelte, src/routes/getting-started/download/index.svelte, src/routes/getting-started/index.svelte, src/routes/index.svelte, src/routes/technology/index.svelte
Fixing the build by using absolute URLs for meta tags. Previous version was introduced in https://github.com/eclipse-che/che-website/pull/75 does not pass the `yarn build` and fails with:
```
> Using @sveltejs/adapter-static
> 404 / (linked from /che/getting-started/)
at file:///home/ibuziuk/git/che-website/node_modules/@sveltejs/kit/dist/chunks/index5.js:432:11
at visit (file:///home/ibuziuk/git/che-website/node_modules/@sveltejs/kit/dist/chunks/index5.js:541:4)
at Object.fn (file:///home/ibuziuk/git/che-website/node_modules/@sveltejs/kit/dist/chunks/index5.js:531:22)
at dequeue (file:///home/ibuziuk/git/che-website/node_modules/@sveltejs/kit/dist/chunks/index5.js:111:42)
at file:///home/ibuziuk/git/che-website/node_modules/@sveltejs/kit/dis …
```
=> fix: using absolute URLs for the Meta Tags

README.md, src/lib/footer/PageFooter.svelte, src/lib/try/TryOnline.svelte
- Updates links to the samples located in [che-samples](https://github.com/che-samples/) to use main branch instead of devfilev2
- Updates year in the footer
- Updates Readmy since Theia is not a default editor anymore
Related issue: https://github.com/eclipse/che/issues/21926
=> chore: update che-samples links

src/lib/try/TryOnline.svelte
Since Devspace Sample "vertx-http-example" id dropped from DS release cycle, we would replace it with another Java sample from Che Sample "Java Guestbook"
=> feat: replace DS vertx sample with Che Java Guestbook sample

src/lib/try/TryOnline.svelte
Update links to Devspaces samples so that they point to floating "latest" tag (except for vertx sample, which is a subject for replacement in https://github.com/eclipse-che/che-website/pull/86 PR)
This PR should be merged as soon as 'latest' tags will exist
=> chore: update DS sample links to point to floating tags

src/lib/try/TryOnline.svelte
we should use '/f?url=' instead of '#' until https://github.com/eclipse/che/issues/21655 is fixed and promoted to workspaces.openshift.com
=> fix: use '/f?url=' instead of # for getting started samples

src/lib/footer/PageFooter.svelte
[![Verify](https://www.eclipse.org/che/contribute.svg)](https://workspaces.openshift.com#https://github.com/eclipse-che/che-website/pull/94)
Related to https://github.com/eclipse/che/issues/22389
=> fix: Update 'Chat' link to Eclipse Cloud Dev Tools Working Group on Slack

src/lib/try/TryOnline.svelte
Removing angular sample in favour of Ollama
=> feat: Adding Ollama Getting Started

src/lib/try/TryOnline.svelte
=> feat: Using devfile.io samples for getting-started

src/lib/try/TryOnline.svelte
Add NodeJS+MongoDB sample, the devfile is located on [registry.devfile.io](https://registry.devfile.io/devfiles/nodejs-mongodb/1.0.0)
Related issue: https://github.com/eclipse-che/che/issues/23429
=> feat: Add NodeJS+MongoDB sample

src/lib/try/TryOnline.svelte
https://www.youtube.com/watch?v=b7xbcTAGNIQ
- https://registry.devfile.io/devfiles/jhipster-online/2.33.1 
- https://registry.devfile.io/viewer/devfiles/community/jhipster-online
=> feat: Adding JHipster devfile
